System Programming :: First Exercise - Manage list of patients (Author: Tonit Biba): src/main.c File Reference
main.c File Reference
Implements the main function.
#include <stdio.h>
#include <libgen.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "option.h"
#include "str_serialize.h"
#include "patient.h"
Macros
#define _POSIX_SOURCE
Functions
int main (int argc, char *argv [])
Detailed Description
Implements the main function.
Copyright (C) 2020 Tonit Biba All rights reserved University of Prishtina, Prishtine, Kosove. tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com
Author
Tonit Biba (tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com)
Date
Date
Sht 30 Maj 2020 09:52:49.PD CEST
Definition in file main.c.
Macro Definition Documentation
_POSIX_SOURCE
#define _POSIX_SOURCE
Definition at line 13 of file main.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 25 of file main.c.
References Option_t::address, Patient_t::address, Option_t::age, Patient_t::age, Option_t::append, Option_t::f_name, Option_t::fp, Get_Attr(), Option_t::list, Option_t::name, Patient_t::name, Option_t::nr_personal, Patient_t::nr_personal, option_free(), option_init(), option_proc(), CString_t::p_str, Patient_init(), Patient_read(), Patient_write(), printFooter(), printHeader(), Option_t::surname, Patient_t::surname, Option_t::test_date, and Patient_t::test_date.