System Programming :: First Exercise - Manage list of patients (Author: Tonit Biba): include/option.h File Reference
option.h File Reference
Implements functions for options and arguments procesing.
#include <stdio.h>
Classes
struct Option_t
Macros
#define _OPTION_H 1_
#define OPT_PATTERN "f:ahlp:n:s:m:c:d:"
Functions
void option_init (Option_t *aoObj)
Initializes the data structure describing the application options.
void option_free (Option_t *aoObj)
Frees the data structure describing the application options.
int option_proc (int argc, char *argv[], Option_t *aoObj)
Handles the passed options from main program.
void option_usage (const char *name)
Writes the usage information.
Detailed Description
Implements functions for options and arguments procesing.
Copyright (C) 2020 Tonit Biba All rights reserved. University of Prishtina, Prishtine, Kosove. tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com.
Author
Tonit Biba (tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com)
Date
Date
Sht 30 Maj 2020 09:52:49.PD CEST
Definition in file option.h.
Macro Definition Documentation
_OPTION_H
#define _OPTION_H 1_
Definition at line 14 of file option.h.
OPT_PATTERN
#define OPT_PATTERN "f:ahlp:n:s:m:c:d:"
Definition at line 18 of file option.h.
Referenced by option_proc().
Function Documentation
option_free()
void option_free (Option_t * option)
Frees the data structure describing the application options.
This functions frees the data structure that describes the specified application options
Parameters
[in,out] option - pointer to the application's options object
Return values
void
Definition at line 64 of file option.c.
References Option_t::address, Option_t::age, Option_t::append, Option_t::f_name, Option_t::fp, Option_t::list, Option_t::name, Option_t::nr_personal, Option_t::surname, and Option_t::test_date.
Referenced by main().
option_init()
void option_init (Option_t * option)
Initializes the data structure describing the application options.
This functions initializes the data structure that describes the specified application options.
Parameters
[in,out] option - pointer to the application's options object
Return values
void
Definition at line 35 of file option.c.
References Option_t::address, Option_t::age, Option_t::append, Option_t::f_name, Option_t::fp, Option_t::list, Option_t::name, Option_t::nr_personal, Option_t::surname, and Option_t::test_date.
Referenced by main().
option_proc()
int option_proc (int argc, char * argv[], Option_t * option)
Handles the passed options from main program.
This functions processes the arguments that are send from main program. application options
Parameters
[in] argc - number of arguments that will be procesed
Definition at line 106 of file option.c.
References Option_t::address, Option_t::age, Option_t::append, Option_t::f_name, Option_t::list, Option_t::name, Option_t::nr_personal, OPT_PATTERN, option_usage(), Option_t::surname, and Option_t::test_date.
Referenced by main().
option_usage()
void option_usage (const char * app_name)
Writes the usage information.
This functions writes the usage information in the stdout and exits with an error
Parameters
[in] app_name - the application name
Return values
void
Definition at line 216 of file option.c.
Referenced by option_proc().