System Programming :: First Exercise - Manage list of patients (Author: Tonit Biba): src/patient.c File Reference
patient.c File Reference
Implements functions for the patients tested with Covid-19.
#include <stdio.h>
#include <malloc.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <string.h>
#include "str_serialize.h"
#include "patient.h"
Macros
#define BUFF_LEN (1024)
Functions
int Patient_init (const char *nr_personal, const char *name, const char *surname, const char *age, const char *address, const char *test_date, Patient_t *const patient)
Initialize the data structure which describes a Patient_t object.
void Patient_free (Patient_t *const patient)
Release an object of type Patient_t.
int Patient_write (FILE *fp, const Patient_t *const patient)
Writes the data structure which describes a Patient_t object.
int Patient_read (FILE *fp, Patient_t *const patient)
Reades the data structure which describes a Patient_t object.
void printHeader ()
Writes the header of table for patient list.
void printFooter (const int total)
Writes the footer of table for patient list.
char * Get_Attr (const char *attr_name, char *arg)
Initialize attribute of Patient_t structure.
int Write_Attr (FILE *fp, const CString_t *const arg)
Initialize attribute of Patient_t structure.
Detailed Description
Implements functions for the patients tested with Covid-19.
Implements functions for the patient with Covid-19.
Copyright (C) 2020 Tonit Biba All rights reserved University of Prishtina, Prishtine, Kosove. tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com
Author
Tonit Biba (tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com)
Date
Date
Sht 30 Maj 2020 09:52:49.PD CEST
Definition in file patient.c.
Macro Definition Documentation
BUFF_LEN
#define BUFF_LEN (1024)
Definition at line 21 of file patient.c.
Referenced by Get_Attr().
Function Documentation
Get_Attr()
char* Get_Attr (const char * attr_name, char * arg)
Initialize attribute of Patient_t structure.
This function initilizes the attribute of Patient_t structure with data from argument or from user input if it is not specified.
Parameters
[in] attr_name - char array attribute name.
[in] arg - char array of argument if it is specified by user.
Return values
NULL in case of error.
arg in case of specified by user argument
char* in case if it has been read by user input.
Definition at line 427 of file patient.c.
References BUFF_LEN.
Referenced by main().
Patient_free()
void Patient_free (Patient_t *const patient)
Release an object of type Patient_t.
Parameters
[in,out] patient - the object to be released
Return values
void
Definition at line 106 of file patient.c.
References Patient_t::address, Patient_t::age, Patient_t::name, Patient_t::nr_personal, CString_t::p_str, Patient_t::surname, and Patient_t::test_date.
Referenced by Patient_init().
Patient_init()
int Patient_init (const char * nr_personal, const char * name, const char * surname, const char * age, const char * address, const char * test_date, Patient_t *const patient)
Initialize the data structure which describes a Patient_t object.
This function initilizes the data structure that describes the specified patient structure
Parameters
[in] nr_personal - char array of personal number
[in] name - char array of name
[in] surname - char array of surname
[in] age - char array of age
[in] address - char array of address
[in] test_date - char array of test_date
[in,out] fp - file pointer in which will be written patient data
Return values
0 in case an error was occured.
1 if patient is initialized successfully.
Definition at line 41 of file patient.c.
References Patient_t::address, Patient_t::age, Patient_t::name, Patient_t::nr_personal, CString_t::p_str, Patient_free(), str_init(), Patient_t::surname, and Patient_t::test_date.
Referenced by main().
Patient_read()
int Patient_read (FILE * fp, Patient_t *const patient)
Reades the data structure which describes a Patient_t object.
This function is used to read a line of file in format of Patient_t structure.
Parameters
[in,out] fp - file pointer in which will be read patient data
[in,out] patient - patient pointer which will be written
Return values
-1 in case of memory allocation fail
0 in case an error was occured.
1 if patient is initialized successfully.
2 if is reached the end of file.
Definition at line 228 of file patient.c.
References Patient_t::address, Patient_t::age, CString_t::length, Patient_t::name, Patient_t::nr_personal, CString_t::p_str, SER_INT_LEN, Patient_t::surname, and Patient_t::test_date.
Referenced by main().
Patient_write()
int Patient_write (FILE * fp, const Patient_t *const patient)
Writes the data structure which describes a Patient_t object.
This function writes the data structure that describes the specified patient structure
Parameters
[in,out] fp - file pointer in which will be written patient data
[in,out] patient - patient pointer which will be written
Return values
0 in case an error was occured.
1 if patient is written successfully.
Definition at line 156 of file patient.c.
References Patient_t::address, Patient_t::age, Patient_t::name, Patient_t::nr_personal, Patient_t::surname, Patient_t::test_date, and Write_Attr().
Referenced by main().
printFooter()
void printFooter (const int total)
Writes the footer of table for patient list.
This functions writes the footer of table in which will be displayed patients data.
Parameters
[in] total - total number of patient in file.
Return values
void
Definition at line 407 of file patient.c.
Referenced by main().
printHeader()
void printHeader ()
Writes the header of table for patient list.
This functions writes the header of table in which will be displayed patients data.
Return values
void
Definition at line 392 of file patient.c.
Referenced by main().
Write_Attr()
int Write_Attr (FILE * fp, const CString_t *const arg)
Initialize attribute of Patient_t structure.
This function initilizes the attribute of Patient_t structure with data from argument or from user input if it is not specified.
Parameters
[in] fp - fp pointer.
[in] arg - CString_t attribute which will be written to file.
Return values
number of files that are written in file.
0 in case of error.
Definition at line 459 of file patient.c.
References CString_t::length, CString_t::p_str, and SER_INT_LEN.
Referenced by Patient_write().