System Programming :: First Exercise - Manage list of patients (Author: Tonit Biba): src/str_serialize.c File Reference
str_serialize.c File Reference
Implements functions for the string file serialization. This fajlli is identicial with file that has been send by prof. Idriz Smajli. Credits to prof. Idriz Smajli.
#include <stdio.h>
#include <malloc.h>
#include <unistd.h>
#include <arpa/inet.h>
#include "str_serialize.h"
Functions
int str_len (const char *str)
Returns the number of characters in a given string.
int str_init (const char *str, CString_t *const c_str)
Initialize a CString_t object.
int str_write (FILE *fp, const CString_t *const c_str)
Writes an input string into the file.
int str_read (FILE *fp, CString_t *const dst)
Reads an string from the file.
Detailed Description
Implements functions for the string file serialization. This fajlli is identicial with file that has been send by prof. Idriz Smajli. Credits to prof. Idriz Smajli.
Copyright (C) 2020 Tonit Biba All rights reserved University of Prishtina, Prishtine, Kosove. tonit.nosp@m..bib.nosp@m.a@hot.nosp@m.mail.nosp@m..com
Author
IS) Dr.techn. Dipl.-Ing. Idriz Smaili (smail.nosp@m.i.id.nosp@m.riz@g.nosp@m.mail.nosp@m..com)
Date
Date
Sht 30 Maj 2020 09:52:49.PD CEST
Definition in file str_serialize.c.
Function Documentation
str_init()
int str_init (const char * str, CString_t *const c_str)
Initialize a CString_t object.
Parameters
[in,out] fp - file pointer
[in] c_str - the input CString_t
Return values
0 in case an error was occured
>0 number of bytes that have been allocated for the string object
Definition at line 52 of file str_serialize.c.
References CString_t::length, CString_t::p_str, and str_len().
Referenced by Patient_init().
str_len()
int str_len (const char * str)
Returns the number of characters in a given string.
Parameters
[in] str - input string
Return values
number of characters
Definition at line 28 of file str_serialize.c.
Referenced by str_init().
str_read()
int str_read (FILE * fp, CString_t *const dst)
Reads an string from the file.
First the four (4) bytes will be read, which indicate the length of the string to be read, and then the string itself will be read.
Parameters
[in,out] fp - file pointer
[out] dst - pointer to the newly allocated string
Return values
0 in case an error was occured
SER_MEM_ERROR error allocating memory was occured
SER_EOF end of file is reached
>0 number of bytes read out from the file
Definition at line 141 of file str_serialize.c.
References CString_t::length, CString_t::p_str, SER_ALLOC_ERROR, SER_EOF, and SER_INT_LEN.
str_write()
int str_write (FILE * fp, const CString_t *const c_str)
Writes an input string into the file.
First the four (4) bytes will be written indicating the length of the string to be written, and then the string itself will be written.
Parameters
[in,out] fp - file pointer
[in] c_str - the input CString_t
Return values
0 in case an error was occured
>0 number of bytes written in the file
Definition at line 94 of file str_serialize.c.
References CString_t::length, CString_t::p_str, and SER_INT_LEN.